[package]
name = "texture-atlasser"
version = "0.1.0"
authors = ["Florian Kaufmann <no@no.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.23.14"
rectangle-pack = "^0.3.0"